FROM jenkins/jenkins:lts

# Pindah ke root untuk install aplikasi
USER root

# Install make dan docker CLI
RUN apt-get update && apt-get install -y make docker.io && apt-get clean

# Masukkan user jenkins ke grup docker agar bisa pakai docker tanpa sudo
RUN usermod -aG docker jenkins

# Balik lagi ke user jenkins demi keamanan
USER jenkins